# Import Python Files
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowFeedbackQuestions(object):
    # Function to Set Up feedbackQuestions.py
    def setupUiFeedbackQuestions(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 700)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color:#00C0FF;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.navigationFrame = QtWidgets.QFrame(self.centralwidget)
        self.navigationFrame.setGeometry(QtCore.QRect(0, 0, 1200, 100))
        self.navigationFrame.setStyleSheet("#navigationFrame{\n"
"    background-color:#0000AF;\n"
"}")
        self.navigationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigationFrame.setObjectName("navigationFrame")
        self.nameOutput = QtWidgets.QLabel(self.navigationFrame)
        self.nameOutput.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.nameOutput.setStyleSheet("#nameOutput{\n"
"    font-weight:bold;\n"
"    font-size:24px;\n"
"    color:#fff;\n"
"}")
        self.nameOutput.setObjectName("nameOutput")
        self.roleOutput = QtWidgets.QLabel(self.navigationFrame)
        self.roleOutput.setGeometry(QtCore.QRect(20, 50, 61, 16))
        self.roleOutput.setStyleSheet("#roleOutput{\n"
"    font-size:16px;\n"
"    font-family:Montserrat;\n"
"    color:#fff;\n"
"}")
        self.roleOutput.setObjectName("roleOutput")
        self.finishPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishPushButton.setGeometry(QtCore.QRect(940, 630, 231, 51))
        self.finishPushButton.setStyleSheet("#finishPushButton{\n"
"    background-color:none;\n"
"    border:4px solid #0000AF;\n"
"    border-radius:20px;\n"
"    font-family:Montserrat;\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    color:#0000AF;\n"
"}")
        self.finishPushButton.setObjectName("finishPushButton")
        self.surveyFrame = QtWidgets.QFrame(self.centralwidget)
        self.surveyFrame.setGeometry(QtCore.QRect(20, 140, 1151, 471))
        self.surveyFrame.setStyleSheet("#surveyFrame{\n"
"    background-color:#FEFCFC;\n"
"    border-radius:25px;\n"
"}")
        self.surveyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyFrame.setObjectName("surveyFrame")
        self.surveyOne = QtWidgets.QLabel(self.surveyFrame)
        self.surveyOne.setGeometry(QtCore.QRect(20, 20, 481, 21))
        self.surveyOne.setStyleSheet("#surveyOne{\n"
"    font-style:Montserrat;\n"
"    font-size:14px;\n"
"}")
        self.surveyOne.setObjectName("surveyOne")
        self.surveyTwo = QtWidgets.QLabel(self.surveyFrame)
        self.surveyTwo.setGeometry(QtCore.QRect(20, 210, 481, 21))
        self.surveyTwo.setStyleSheet("#surveyTwo{\n"
"    font-style:Montserrat;\n"
"    font-size:14px;\n"
"}")
        self.surveyTwo.setObjectName("surveyTwo")
        self.surveyFour = QtWidgets.QLabel(self.surveyFrame)
        self.surveyFour.setGeometry(QtCore.QRect(570, 20, 521, 21))
        self.surveyFour.setStyleSheet("#surveyFour{\n"
"    font-style:Montserrat;\n"
"    font-size:14px;\n"
"}")
        self.surveyFour.setObjectName("surveyFour")
        self.surveyThree = QtWidgets.QLabel(self.surveyFrame)
        self.surveyThree.setGeometry(QtCore.QRect(20, 390, 481, 21))
        self.surveyThree.setStyleSheet("#surveyThree{\n"
"    font-style:Montserrat;\n"
"    font-size:14px;\n"
"}")
        self.surveyThree.setObjectName("surveyThree")
        self.surveyFive = QtWidgets.QLabel(self.surveyFrame)
        self.surveyFive.setGeometry(QtCore.QRect(570, 210, 551, 21))
        self.surveyFive.setStyleSheet("#surveyFive{\n"
"    font-style:Montserrat;\n"
"    font-size:14px;\n"
"}")
        self.surveyFive.setObjectName("surveyFive")
        self.surveyOneFrame = QtWidgets.QFrame(self.surveyFrame)
        self.surveyOneFrame.setGeometry(QtCore.QRect(20, 50, 120, 151))
        self.surveyOneFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyOneFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyOneFrame.setObjectName("surveyOneFrame")
        self.surveyOneExcellent = QtWidgets.QRadioButton(self.surveyOneFrame)
        self.surveyOneExcellent.setGeometry(QtCore.QRect(0, 120, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyOneExcellent.setFont(font)
        self.surveyOneExcellent.setObjectName("surveyOneExcellent")
        self.surveyOneVeryPoor = QtWidgets.QRadioButton(self.surveyOneFrame)
        self.surveyOneVeryPoor.setGeometry(QtCore.QRect(0, 0, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyOneVeryPoor.setFont(font)
        self.surveyOneVeryPoor.setObjectName("surveyOneVeryPoor")
        self.surveyOneGood = QtWidgets.QRadioButton(self.surveyOneFrame)
        self.surveyOneGood.setGeometry(QtCore.QRect(0, 90, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyOneGood.setFont(font)
        self.surveyOneGood.setObjectName("surveyOneGood")
        self.surveyOnePoor = QtWidgets.QRadioButton(self.surveyOneFrame)
        self.surveyOnePoor.setGeometry(QtCore.QRect(0, 30, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyOnePoor.setFont(font)
        self.surveyOnePoor.setObjectName("surveyOnePoor")
        self.surveyOneNeutral = QtWidgets.QRadioButton(self.surveyOneFrame)
        self.surveyOneNeutral.setGeometry(QtCore.QRect(0, 60, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyOneNeutral.setFont(font)
        self.surveyOneNeutral.setObjectName("surveyOneNeutral")
        self.surveyTwoFrame = QtWidgets.QFrame(self.surveyFrame)
        self.surveyTwoFrame.setGeometry(QtCore.QRect(20, 230, 201, 151))
        self.surveyTwoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyTwoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyTwoFrame.setObjectName("surveyTwoFrame")
        self.surveyTwoExtreme = QtWidgets.QRadioButton(self.surveyTwoFrame)
        self.surveyTwoExtreme.setGeometry(QtCore.QRect(0, 130, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyTwoExtreme.setFont(font)
        self.surveyTwoExtreme.setObjectName("surveyTwoExtreme")
        self.surveyTwoNotAtAll = QtWidgets.QRadioButton(self.surveyTwoFrame)
        self.surveyTwoNotAtAll.setGeometry(QtCore.QRect(0, 10, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyTwoNotAtAll.setFont(font)
        self.surveyTwoNotAtAll.setObjectName("surveyTwoNotAtAll")
        self.surveyTwoVery = QtWidgets.QRadioButton(self.surveyTwoFrame)
        self.surveyTwoVery.setGeometry(QtCore.QRect(0, 100, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyTwoVery.setFont(font)
        self.surveyTwoVery.setObjectName("surveyTwoVery")
        self.surveyTwoSlightly = QtWidgets.QRadioButton(self.surveyTwoFrame)
        self.surveyTwoSlightly.setGeometry(QtCore.QRect(0, 40, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyTwoSlightly.setFont(font)
        self.surveyTwoSlightly.setObjectName("surveyTwoSlightly")
        self.surveyTwoModerate = QtWidgets.QRadioButton(self.surveyTwoFrame)
        self.surveyTwoModerate.setGeometry(QtCore.QRect(0, 70, 171, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyTwoModerate.setFont(font)
        self.surveyTwoModerate.setObjectName("surveyTwoModerate")
        self.surveyThreeFrame = QtWidgets.QFrame(self.surveyFrame)
        self.surveyThreeFrame.setGeometry(QtCore.QRect(20, 410, 120, 51))
        self.surveyThreeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyThreeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyThreeFrame.setObjectName("surveyThreeFrame")
        self.surveyThreeNo = QtWidgets.QRadioButton(self.surveyThreeFrame)
        self.surveyThreeNo.setGeometry(QtCore.QRect(0, 30, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyThreeNo.setFont(font)
        self.surveyThreeNo.setObjectName("surveyThreeNo")
        self.surveyThreeYes = QtWidgets.QRadioButton(self.surveyThreeFrame)
        self.surveyThreeYes.setGeometry(QtCore.QRect(0, 5, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyThreeYes.setFont(font)
        self.surveyThreeYes.setObjectName("surveyThreeYes")
        self.surveyFourFrame = QtWidgets.QFrame(self.surveyFrame)
        self.surveyFourFrame.setGeometry(QtCore.QRect(570, 50, 141, 141))
        self.surveyFourFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyFourFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyFourFrame.setObjectName("surveyFourFrame")
        self.surveyFourVerySat = QtWidgets.QRadioButton(self.surveyFourFrame)
        self.surveyFourVerySat.setGeometry(QtCore.QRect(0, 120, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVerySat.setFont(font)
        self.surveyFourVerySat.setObjectName("surveyFourVerySat")
        self.surveyFourDis = QtWidgets.QRadioButton(self.surveyFourFrame)
        self.surveyFourDis.setGeometry(QtCore.QRect(0, 30, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourDis.setFont(font)
        self.surveyFourDis.setObjectName("surveyFourDis")
        self.surveyFourVeryDis = QtWidgets.QRadioButton(self.surveyFourFrame)
        self.surveyFourVeryDis.setGeometry(QtCore.QRect(0, 0, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis.setFont(font)
        self.surveyFourVeryDis.setObjectName("surveyFourVeryDis")
        self.surveyFourSatisfied = QtWidgets.QRadioButton(self.surveyFourFrame)
        self.surveyFourSatisfied.setGeometry(QtCore.QRect(0, 90, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourSatisfied.setFont(font)
        self.surveyFourSatisfied.setObjectName("surveyFourSatisfied")
        self.surveyFourNeutral = QtWidgets.QRadioButton(self.surveyFourFrame)
        self.surveyFourNeutral.setGeometry(QtCore.QRect(0, 60, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourNeutral.setFont(font)
        self.surveyFourNeutral.setObjectName("surveyFourNeutral")
        self.surveyFiveFrame = QtWidgets.QFrame(self.surveyFrame)
        self.surveyFiveFrame.setGeometry(QtCore.QRect(570, 230, 201, 151))
        self.surveyFiveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.surveyFiveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.surveyFiveFrame.setObjectName("surveyFiveFrame")
        self.surveyFourVeryDis_6 = QtWidgets.QRadioButton(self.surveyFiveFrame)
        self.surveyFourVeryDis_6.setGeometry(QtCore.QRect(0, 130, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis_6.setFont(font)
        self.surveyFourVeryDis_6.setObjectName("surveyFourVeryDis_6")
        self.surveyFourVeryDis_4 = QtWidgets.QRadioButton(self.surveyFiveFrame)
        self.surveyFourVeryDis_4.setGeometry(QtCore.QRect(0, 70, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis_4.setFont(font)
        self.surveyFourVeryDis_4.setObjectName("surveyFourVeryDis_4")
        self.surveyFourVeryDis_3 = QtWidgets.QRadioButton(self.surveyFiveFrame)
        self.surveyFourVeryDis_3.setGeometry(QtCore.QRect(0, 40, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis_3.setFont(font)
        self.surveyFourVeryDis_3.setObjectName("surveyFourVeryDis_3")
        self.surveyFourVeryDis_2 = QtWidgets.QRadioButton(self.surveyFiveFrame)
        self.surveyFourVeryDis_2.setGeometry(QtCore.QRect(0, 10, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis_2.setFont(font)
        self.surveyFourVeryDis_2.setObjectName("surveyFourVeryDis_2")
        self.surveyFourVeryDis_5 = QtWidgets.QRadioButton(self.surveyFiveFrame)
        self.surveyFourVeryDis_5.setGeometry(QtCore.QRect(0, 100, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.surveyFourVeryDis_5.setFont(font)
        self.surveyFourVeryDis_5.setObjectName("surveyFourVeryDis_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameOutput.setText(_translate("MainWindow", "Juan Dela Cruz"))
        self.roleOutput.setText(_translate("MainWindow", "Member"))
        self.finishPushButton.setText(_translate("MainWindow", "Finish Shopping"))
        self.surveyOne.setText(_translate("MainWindow", "How would you rate your overall experience using our Smart Shopping Cart?"))
        self.surveyTwo.setText(_translate("MainWindow", "How would you rate your overall experience using our Smart Shopping Cart?"))
        self.surveyFour.setText(_translate("MainWindow", "How satisfied were you with the accuracy of product recognition by the Smart Cart?"))
        self.surveyThree.setText(_translate("MainWindow", "Did the Smart Cart enhance the efficiency of your shopping experience?"))
        self.surveyFive.setText(_translate("MainWindow", "How likely are you to recommend the Smart Shopping Cart to a friend or family member?"))
        self.surveyOneExcellent.setText(_translate("MainWindow", "Excellent"))
        self.surveyOneVeryPoor.setText(_translate("MainWindow", "Very Poor"))
        self.surveyOneGood.setText(_translate("MainWindow", "Good"))
        self.surveyOnePoor.setText(_translate("MainWindow", "Poor"))
        self.surveyOneNeutral.setText(_translate("MainWindow", "Neutral"))
        self.surveyTwoExtreme.setText(_translate("MainWindow", "Extremely user-friendly"))
        self.surveyTwoNotAtAll.setText(_translate("MainWindow", "Not at all user-friendly"))
        self.surveyTwoVery.setText(_translate("MainWindow", "Very user-friendly"))
        self.surveyTwoSlightly.setText(_translate("MainWindow", "Slightly user-friendly"))
        self.surveyTwoModerate.setText(_translate("MainWindow", "Moderately user-friendly"))
        self.surveyThreeNo.setText(_translate("MainWindow", "No"))
        self.surveyThreeYes.setText(_translate("MainWindow", "Yes"))
        self.surveyFourVerySat.setText(_translate("MainWindow", "Very Satisfied"))
        self.surveyFourDis.setText(_translate("MainWindow", "Dissatisfied"))
        self.surveyFourVeryDis.setText(_translate("MainWindow", "Very Dissatisfied"))
        self.surveyFourSatisfied.setText(_translate("MainWindow", "Satisfied"))
        self.surveyFourNeutral.setText(_translate("MainWindow", "Neutral"))
        self.surveyFourVeryDis_6.setText(_translate("MainWindow", "Extremely likely"))
        self.surveyFourVeryDis_4.setText(_translate("MainWindow", "Neutral"))
        self.surveyFourVeryDis_3.setText(_translate("MainWindow", "Slightly likely"))
        self.surveyFourVeryDis_2.setText(_translate("MainWindow", "Not likely at all"))
        self.surveyFourVeryDis_5.setText(_translate("MainWindow", "Very likely"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowFeedbackQuestions()
    ui.setupUiFeedbackQuestions(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
